In [5]:
import numpy as np
import pandas as pd
import os

In [8]:
path_csv = r'/home/jvdata/Documentos/Case-SEGMEDIC/src/data/bronze/Desafio-Segmedic-Python.csv'

In [9]:
print(path_csv)

/home/jvdata/Documentos/Case-SEGMEDIC/src/data/bronze/Desafio-Segmedic-Python.csv

In [10]:
df = pd.read_csv(path_csv, sep=";")

Carregando Data Frame para uma pré visualização

In [ ]:
df.head(10)

,data_atendimento,paciente_id,nomeprocedimento,grupoprocedimento,valor_pago,retorno,nomeunidade,formapagamento,idprofissional
0,30/01/2024,104593.0,Rx Tornozelo Esquerdo,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
1,30/01/2024,104593.0,Rx Joelho,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
2,06/02/2024,166899.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18052.0
3,22/02/2024,188620.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18190.0
4,26/02/2024,45111.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18188.0
5,27/03/2024,18877.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
6,02/04/2024,133667.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
7,05/04/2024,163495.0,Teste Rápido Gravidez (Bhcg),Enfermaria,"16,99",Não,Centro Medico Matriz,PIX,18298.0
8,18/04/2024,217215.0,Tc Lombar,Tomografia,229,Não,Centro Medico Matriz,PIX,17187.0
9,06/05/2024,166899.0,Vitamina B12 (B12),Exames Laboratoriais,"19,99",Não,Centro Medico Matriz,PIX,17882.0

Verificando a quantidade de nulos

In [ ]:
df.isnull().sum()

data_atendimento      0
paciente_id           7
nomeprocedimento      0
grupoprocedimento     0
valor_pago           16
retorno               0
nomeunidade           0
formapagamento        0
idprofissional       11
dtype: int64

In [ ]:
df_limpo = df.dropna()

Valores nulos da tabela foram limpos

In [ ]:
df_limpo.isnull().sum()

data_atendimento     0
paciente_id          0
nomeprocedimento     0
grupoprocedimento    0
valor_pago           0
retorno              0
nomeunidade          0
formapagamento       0
idprofissional       0
dtype: int64

In [ ]:
df_limpo.dtypes

data_atendimento         str
paciente_id          float64
nomeprocedimento         str
grupoprocedimento        str
valor_pago               str
retorno                  str
nomeunidade              str
formapagamento           str
idprofissional       float64
dtype: object

In [ ]:
df_limpo.head(31)

,data_atendimento,paciente_id,nomeprocedimento,grupoprocedimento,valor_pago,retorno,nomeunidade,formapagamento,idprofissional
0,30/01/2024,104593.0,Rx Tornozelo Esquerdo,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
1,30/01/2024,104593.0,Rx Joelho,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
2,06/02/2024,166899.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18052.0
3,22/02/2024,188620.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18190.0
4,26/02/2024,45111.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18188.0
5,27/03/2024,18877.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
6,02/04/2024,133667.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
7,05/04/2024,163495.0,Teste Rápido Gravidez (Bhcg),Enfermaria,"16,99",Não,Centro Medico Matriz,PIX,18298.0
8,18/04/2024,217215.0,Tc Lombar,Tomografia,229,Não,Centro Medico Matriz,PIX,17187.0
9,06/05/2024,166899.0,Vitamina B12 (B12),Exames Laboratoriais,"19,99",Não,Centro Medico Matriz,PIX,17882.0
10,09/05/2024,220158.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,11634.0
11,27/05/2024,202730.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,11634.0
12,06/06/2024,163495.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,11634.0
13,10/06/2024,222166.0,Sifilis - Vdrl (Vdrl),Exames Laboratoriais,"9,99",Não,Centro Medico Matriz,PIX,17882.0
14,10/07/2024,232510.0,Consulta Clinica Geral,Clinica Geral,29,Não,Centro Medico Matriz,PIX,17955.0
15,25/10/2024,184069.0,Consulta Clinica Geral,Clinica Geral,29,Não,Centro Medico Matriz,PIX,66.0
16,26/12/2024,241578.0,Laudo 2 Horas - Urina Tipo I,Exames Laboratoriais,"11,99",Não,Centro Medico Matriz,PIX,18335.0
17,17/01/2025,241579.0,Hepatite B - Anti - Hbe (Qhbe),Exames Laboratoriais,"21,09",Não,Centro Medico Matriz,PIX,17882.0
18,17/01/2025,241579.0,Hepatite B - Anti - Hbc Igm (Qhbcm),Exames Laboratoriais,"30,33",Não,Centro Medico Matriz,PIX,17882.0
19,11/03/2025,250559.0,Tsh - Hormonio Tireoestimulante - Ultrassensiv...,Exames Laboratoriais,"13,68",Não,Centro Medico Matriz,PIX,17882.0
20,10/04/2025,254624.0,Rx Torax - 2 Incidencias,Raio X,84,Não,Centro Medico Matriz,PIX,17187.0
21,22/04/2025,254624.0,Hcg - Gonadotrofina Corionica - Quantitativo (...,Exames Laboratoriais,"32,19",Não,Centro Medico Matriz,PIX,18341.0
22,22/07/2025,236582.0,Triglicerides (Trigl),Exames Laboratoriais,"9,19",Não,Centro Medico Matriz,PIX,17927.0
23,22/07/2025,236582.0,Tsh - Hormonio Tireoestimulante - Ultrassensiv...,Exames Laboratoriais,"13,68",Não,Centro Medico Matriz,PIX,17927.0
24,22/07/2025,236582.0,Glicose - Tempos (Glicotempo),Exames Laboratoriais,"19,99",Não,Centro Medico Matriz,PIX,17922.0
25,22/07/2025,236582.0,Hemoglobina Glicada (Glicemia Media Estimada) ...,Exames Laboratoriais,"12,64",Não,Centro Medico Matriz,PIX,17927.0
26,22/07/2025,236582.0,Hemograma (Hedta),Exames Laboratoriais,"9,9",Não,Centro Medico Matriz,PIX,17927.0
27,22/07/2025,236582.0,Insulina (Insul),Exames Laboratoriais,"22,99",Não,Centro Medico Matriz,PIX,17922.0
28,22/07/2025,236582.0,Potassio (K),Exames Laboratoriais,"6,89",Não,Centro Medico Matriz,PIX,17927.0
29,22/07/2025,236582.0,Lipase (Lipas),Exames Laboratoriais,"14,94",Não,Centro Medico Matriz,PIX,17927.0
30,22/07/2025,236582.0,Trab - Anticorpo Anti Receptor De Tsh (Trab),Exames Laboratoriais,"103,49",Não,Centro Medico Matriz,PIX,17927.0

Será preciso mudar o data type de paciente_id e profissional_id porque não tem sentido considerar essa coluna como float sendo um indentificador.