In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
path_csv = r'/home/jvdata/Documentos/Case-SEGMEDIC/src/data/bronze/Desafio-Segmedic-Python.csv'

In [4]:
df = pd.read_csv(path_csv, sep=";")

Carregando Data Frame para uma pré visualização

In [5]:
df.head(10)

,data_atendimento,paciente_id,nomeprocedimento,grupoprocedimento,valor_pago,retorno,nomeunidade,formapagamento,idprofissional
0,30/01/2024,104593.0,Rx Tornozelo Esquerdo,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
1,30/01/2024,104593.0,Rx Joelho,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
2,06/02/2024,166899.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18052.0
3,22/02/2024,188620.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18190.0
4,26/02/2024,45111.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18188.0
5,27/03/2024,18877.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
6,02/04/2024,133667.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,17955.0
7,05/04/2024,163495.0,Teste Rápido Gravidez (Bhcg),Enfermaria,"16,99",Não,Centro Medico Matriz,PIX,18298.0
8,18/04/2024,217215.0,Tc Lombar,Tomografia,229,Não,Centro Medico Matriz,PIX,17187.0
9,06/05/2024,166899.0,Vitamina B12 (B12),Exames Laboratoriais,"19,99",Não,Centro Medico Matriz,PIX,17882.0

Verificando a quantidade de nulos

In [6]:
df.isnull().sum()

data_atendimento      0
paciente_id           7
nomeprocedimento      0
grupoprocedimento     0
valor_pago           16
retorno               0
nomeunidade           0
formapagamento        0
idprofissional       11
dtype: int64

In [7]:
df_limpo = df.dropna()

Valores nulos da tabela foram limpos

In [8]:
df_limpo.isnull().sum()

data_atendimento     0
paciente_id          0
nomeprocedimento     0
grupoprocedimento    0
valor_pago           0
retorno              0
nomeunidade          0
formapagamento       0
idprofissional       0
dtype: int64

In [9]:
df_limpo.dtypes

data_atendimento         str
paciente_id          float64
nomeprocedimento         str
grupoprocedimento        str
valor_pago               str
retorno                  str
nomeunidade              str
formapagamento           str
idprofissional       float64
dtype: object

In [10]:
df_limpo.head()

,data_atendimento,paciente_id,nomeprocedimento,grupoprocedimento,valor_pago,retorno,nomeunidade,formapagamento,idprofissional
0,30/01/2024,104593.0,Rx Tornozelo Esquerdo,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
1,30/01/2024,104593.0,Rx Joelho,Raio X,49,Não,Centro Medico Matriz,PIX,18252.0
2,06/02/2024,166899.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18052.0
3,22/02/2024,188620.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18190.0
4,26/02/2024,45111.0,Consulta Clinica Geral,Clinica Geral,19,Não,Centro Medico Matriz,PIX,18188.0

Será preciso mudar o data type de paciente_id, profissional_id, valor_pago e data_atendimento porque não tem sentido considerar as paciente e profissional como float sendo idenficadores e valor pago realizar a substituição da vírgula por ponto para mudar o data type para fazer sentido com a coluna. Além da coluna data_atendimento não estar com o type correto o que dificultaria para montar um filtro com essa coluna

In [11]:
df_limpo["paciente_id"] = df_limpo["paciente_id"].astype(int)

df_limpo["idprofissional"] = df_limpo["idprofissional"].astype(int)

df_limpo["valor_pago"] = df_limpo["valor_pago"].str.replace(',', '.').astype(float)

In [12]:
df_limpo["data_atendimento"] = pd.to_datetime(df_limpo["data_atendimento"], dayfirst=True)

In [13]:
df_limpo.dtypes

data_atendimento     datetime64[us]
paciente_id                   int64
nomeprocedimento                str
grupoprocedimento               str
valor_pago                  float64
retorno                         str
nomeunidade                     str
formapagamento                  str
idprofissional                int64
dtype: object

In [14]:
df_limpo.head()

,data_atendimento,paciente_id,nomeprocedimento,grupoprocedimento,valor_pago,retorno,nomeunidade,formapagamento,idprofissional
0,2024-01-30,104593,Rx Tornozelo Esquerdo,Raio X,49.0,Não,Centro Medico Matriz,PIX,18252
1,2024-01-30,104593,Rx Joelho,Raio X,49.0,Não,Centro Medico Matriz,PIX,18252
2,2024-02-06,166899,Consulta Clinica Geral,Clinica Geral,19.0,Não,Centro Medico Matriz,PIX,18052
3,2024-02-22,188620,Consulta Clinica Geral,Clinica Geral,19.0,Não,Centro Medico Matriz,PIX,18190
4,2024-02-26,45111,Consulta Clinica Geral,Clinica Geral,19.0,Não,Centro Medico Matriz,PIX,18188

In [15]:
df_limpo.rename(columns={'data_atendimento': 'Data_Atendimento',
                         'paciente_id': 'ID_paciente',
                         'nomeprocedimento': 'Nome_procedimento',
                         'grupoprocedimento': 'Categoria_procedimento',
                         'nomeunidade': 'Unidade',
                         'formapagamento':'Metodo_pagamento',
                         'idprofissional': 'ID_profissional'}, inplace = True)

In [16]:
df_limpo.to_csv('Dados_limpos.csv', index=False, sep=';', encoding='utf-8-sig')